{-# LANGUAGE OverloadedStrings #-}

module Distribution.Nix.Builtin (optionalBuiltins) where

import qualified Data.Set as S
import Data.Text (Text)
import qualified Data.Text as T

optionalBuiltins :: [Text] -> [Text]
optionalBuiltins = map makeOptional
  where
    makeOptional dep
      | S.member dep builtin = T.append dep " ? null"
      | otherwise = dep

    builtin = S.fromList
              [ "allout", "allout-widgets"
              , "ansi-color"
              , "antlr-mode"
              , "artist"
              , "bs"
              , "cedet"
              , "cfengine"
              , "chart"
              , "checkdoc"
              , "cl-lib"
              , "cwarn"
              , "delim-col"
              , "dunnet"
              , "ebnf2ps"
              , "ede"
              , "ediff"
              , "edmacro"
              , "eieio", "eieio-core"
              , "epg"
              , "erc"
              , "ert"
              , "eshell"
              , "feedmail"
              , "find-cmd"
              , "finder"
              , "flymake"
              , "foldout"
              , "footnote"
              , "gamegrid"
              , "gnus"
              , "hippie-exp"
              , "htmlfontify"
              , "icalendar"
              , "idlwave"
              , "image-dired"
              , "info-xref"
              , "inversion"
              , "isearchb"
              , "js", "json"
              , "linum"
              , "master"
              , "md4"
              , "meta-mode"
              , "mh-e"
              , "mixal-mode"
              , "newsticker"
              , "ntlm"
              , "package"
              , "printing"
              , "ps-mode"
              , "ps-print"
              , "pulse"
              , "python"
              , "regi"
              , "remember"
              , "repeat"
              , "ruby-mode"
              , "ruler-mode"
              , "savehist"
              , "semantic"
              , "sh-script"
              , "sql"
              , "srecode"
              , "tabulated-list"
              , "tetris"
              , "thingatpt"
              , "tildify"
              , "timeclock"
              , "url"
              , "vera-mode"
              , "viper"
              , "wdired"
              , "whitespace"
              , "woman"
              ]
